"""Feature-spec registry (append-only, v1 frozen) and the Recipe.

The v1 feature spec is the one the committed champion was trained on. If its
output changes, every v1 model silently receives different inputs at
inference than it was trained on. So v1's output is frozen against a golden
fixture, tests/fixtures/v1_features_golden.npz, generated by the PRE-registry
code (commit 5f2b107, run from a git worktree) on make_universe_bars(120,
seed=123). The fixture stores the input bars as well as the expected
features, so the test exercises only the feature code (not the platform's
synthetic-data generation).

Why a tolerance and not a hash: a byte-exact digest is not portable. numpy
reductions / libm can differ by an ulp or so between macOS and Linux, and
the first version of this test (a sha256 of values printed to 10 significant
digits) failed on Linux CI: dozens of values sit within 1e-13 relative of a
10-digit rounding boundary, so ulp noise flips the digest. The comparison is
instead: exact column names/order, exact index, exact NaN mask, and
np.testing.assert_allclose(rtol=1e-9, atol=1e-12) on the finite values.
rtol=1e-9 leaves ~4 orders of magnitude over the largest ulp amplification
in these formulas (z_20_logp's (ln C - mean)/std cancellation, ~1e-13), and
atol=1e-12 covers near-zero returns whose absolute error is ~1e-15. Any real
change to a feature definition moves values by far more (see the mutation
tests below).
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from wolfpack_worker.analyst import features
from wolfpack_worker.analyst.features import FEATURE_SPECS, FeatureSpec, get_feature_spec
from wolfpack_worker.analyst.recipe import (
    LABELS,
    V1_RECIPE_PATH,
    Recipe,
    RecipeError,
    load_recipe_file,
    load_v1_recipe,
)

GOLDEN = Path(__file__).parent / "fixtures" / "v1_features_golden.npz"
RTOL, ATOL = 1e-9, 1e-12

# recipe_id of recipes/analyst/v1.toml. Changing ANY recipe field changes
# this id, i.e. it is a different recipe (a new trial), never "v1 edited".
# (A sha256 of canonical JSON text: portable, unlike hashes of computed floats.)
V1_RECIPE_ID = "a8e2709b0d8e"


@pytest.fixture(scope="module")
def golden():
    z = np.load(GOLDEN)
    assert str(z["base_commit"]) == "5f2b107"
    idx = pd.DatetimeIndex(z["index_ns"]).tz_localize("UTC")
    bars = {t: pd.DataFrame(z[f"bars_{t}"], index=idx, columns=list(z["bar_columns"])) for t in z["tickers"]}
    return z, bars, idx


def assert_matches_golden(feats, z, idx) -> None:
    assert sorted(feats) == list(z["tickers"])
    for t in z["tickers"]:
        f = feats[t]
        assert list(f.columns) == list(z["feature_names"]), "column names/order changed"
        assert (f.index == idx).all(), "index changed"
        got, want = f.to_numpy(dtype=np.float64), z[f"features_{t}"]
        assert got.shape == want.shape
        np.testing.assert_array_equal(np.isnan(got), np.isnan(want), err_msg=f"{t}: NaN mask changed")
        finite = ~np.isnan(want)
        np.testing.assert_allclose(got[finite], want[finite], rtol=RTOL, atol=ATOL, err_msg=f"{t}: values changed")


# --- feature-spec registry --------------------------------------------------------


def test_v1_spec_output_is_frozen(golden):
    z, bars, idx = golden
    assert_matches_golden(get_feature_spec("v1").build_fn(bars), z, idx)


def test_golden_fixture_is_not_vacuous(golden):
    z, _, _ = golden
    assert list(z["feature_names"]) == list(features.FEATURE_NAMES)
    n_finite = sum(int((~np.isnan(z[f"features_{t}"])).sum()) for t in z["tickers"])
    assert n_finite > 5000  # 5 tickers x ~70 post-warmup rows x 12 features (+ partial)


def test_freeze_catches_a_changed_feature_definition(golden, monkeypatch):
    """Mutation check: a 20-bar window silently becoming 19 bars (vol_20,
    SMA20, z_20, logvol_ratio_20 all move) must fail the freeze."""
    z, bars, idx = golden
    real = features._rolling
    monkeypatch.setattr(features, "_rolling", lambda v, w, fn: real(v, 19 if w == 20 else w, fn))
    with pytest.raises(AssertionError):
        assert_matches_golden(get_feature_spec("v1").build_fn(bars), z, idx)


def test_freeze_catches_a_tiny_value_drift(golden):
    z, bars, idx = golden
    feats = get_feature_spec("v1").build_fn(bars)
    t = str(z["tickers"][0])
    feats[t] = feats[t].copy()
    feats[t]["rsi_14"] = feats[t]["rsi_14"] * (1 + 1e-7)
    with pytest.raises(AssertionError, match="values changed"):
        assert_matches_golden(feats, z, idx)


def test_freeze_catches_reordered_columns_and_nan_mask_changes(golden):
    z, bars, idx = golden
    feats = get_feature_spec("v1").build_fn(bars)
    t = str(z["tickers"][0])
    swapped = dict(feats)
    cols = list(feats[t].columns)
    swapped[t] = feats[t][[cols[1], cols[0], *cols[2:]]]
    with pytest.raises(AssertionError, match="order"):
        assert_matches_golden(swapped, z, idx)
    masked = dict(feats)
    masked[t] = feats[t].copy()
    masked[t].iloc[-1, 0] = np.nan
    with pytest.raises(AssertionError, match="NaN mask"):
        assert_matches_golden(masked, z, idx)


def test_v1_spec_names_and_warmup_are_frozen():
    spec = FEATURE_SPECS["v1"]
    assert isinstance(spec, FeatureSpec)
    assert spec.names == (
        "r_1", "r_5", "r_20", "vol_20", "vol_ratio_5_20", "ma_spread_20_50",
        "z_20_logp", "rsi_14", "hl_range", "logvol_ratio_20", "spy_r_1", "spy_r_5",
    )
    assert spec.warmup_bars == 50


def test_legacy_v1_aliases_still_point_at_v1():
    assert features.FEATURE_SPEC_VERSION == "v1"
    assert features.FEATURE_NAMES == FEATURE_SPECS["v1"].names
    assert FEATURE_SPECS["v1"].build_fn is features.build_features


def test_unknown_spec_raises_keyerror_with_known_versions():
    with pytest.raises(KeyError, match="v1"):
        get_feature_spec("v0")


def test_registry_is_read_only():
    with pytest.raises(TypeError):
        FEATURE_SPECS["v2"] = FEATURE_SPECS["v1"]  # type: ignore[index]


# --- recipe ------------------------------------------------------------------------


def test_v1_recipe_matches_the_first_champion_settings():
    r = load_v1_recipe()
    assert r.feature_spec_version == "v1"
    assert r.label == "next_open_to_open_sign_v1" and r.label in LABELS
    assert r.num_boost_round == 300
    assert r.threshold == 0.5
    assert r.universe == ("SPY", "QQQ", "AAPL", "JPM", "XOM")
    assert r.train_since == "2016-01-04"
    assert dict(r.xgb_params) == {
        "objective": "binary:logistic",
        "max_depth": 3,
        "learning_rate": 0.03,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "min_child_weight": 20,
        "reg_lambda": 1.0,
        "tree_method": "hist",
        "seed": 42,
    }


def test_v1_recipe_matches_committed_champion_manifest_params():
    manifest = json.loads(
        (Path(__file__).resolve().parents[1] / "models/analyst/champion/manifest.json").read_text()
    )
    r = load_v1_recipe()
    assert {**r.xgb_params, "num_boost_round": r.num_boost_round} == manifest["model_params"]


def test_v1_recipe_id_is_pinned():
    assert load_v1_recipe().recipe_id == V1_RECIPE_ID


def test_recipe_id_is_canonical_and_order_independent():
    r = load_v1_recipe()
    d = r.to_dict()
    shuffled = dict(reversed(list(d.items())))
    shuffled["xgb_params"] = dict(reversed(list(d["xgb_params"].items())))
    assert Recipe.from_dict(shuffled).recipe_id == r.recipe_id
    assert len(r.recipe_id) == 12
    assert r.recipe_id == hashlib.sha256(r.canonical_json().encode()).hexdigest()[:12]
    assert json.loads(r.canonical_json()) == d


@pytest.mark.parametrize(
    "change",
    [
        {"num_boost_round": 301},
        {"train_since": "2017-01-03"},
        {"xgb_params": {"max_depth": 4}},
        {"xgb_params": {"seed": 43}},
    ],
)
def test_any_change_gives_a_different_recipe_id(change):
    d = load_v1_recipe().to_dict()
    for k, v in change.items():
        if isinstance(v, dict):
            d[k] = {**d[k], **v}
        else:
            d[k] = v
    assert Recipe.from_dict(d).recipe_id != load_v1_recipe().recipe_id


@pytest.mark.parametrize(
    "patch,match",
    [
        ({"feature_spec_version": "v9"}, "feature_spec_version"),
        ({"label": "close_to_close"}, "label"),
        ({"threshold": 0.55}, "threshold"),
        ({"universe": ["SPY", "QQQ"]}, "universe"),
        ({"num_boost_round": 0}, "num_boost_round"),
        ({"train_since": "yesterday"}, "train_since"),
        ({"surprise": 1}, "unknown"),
        ({"xgb_params": {"objective": "reg:squarederror"}}, "objective"),
        ({"xgb_params": {"objective": "binary:logistic", "nthread": 8}}, "nthread"),
        ({"xgb_params": {"objective": "binary:logistic", "max_depth": [3]}}, "scalar"),
    ],
)
def test_recipe_validation(patch, match):
    d = load_v1_recipe().to_dict()
    d.update(patch)
    with pytest.raises(RecipeError, match=match):
        Recipe.from_dict(d)


def test_missing_key_is_rejected():
    d = load_v1_recipe().to_dict()
    del d["threshold"]
    with pytest.raises(RecipeError, match="missing"):
        Recipe.from_dict(d)


def test_load_recipe_file_accepts_plain_recipe_and_registration_tables(tmp_path):
    plain = V1_RECIPE_PATH.read_text()
    (tmp_path / "plain.toml").write_text(plain)
    assert load_recipe_file(tmp_path / "plain.toml") == load_v1_recipe()
    reg = 'trial_number = 1\nregistered = 2026-10-01\nhypothesis = "x"\n\n' + "\n".join(
        ("[recipe.xgb_params]" if line.strip() == "[xgb_params]" else line)
        for line in plain.splitlines()
    )
    # Top-level recipe keys must sit under [recipe] in a registration file.
    reg = reg.replace('hypothesis = "x"\n', 'hypothesis = "x"\n\n[recipe]\n')
    (tmp_path / "reg.toml").write_text(reg)
    assert load_recipe_file(tmp_path / "reg.toml") == load_v1_recipe()
